apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
    backstage.io/kubernetes-id: my-poc-template
spec:
    type: NodePort
    selector:
        app: app
    ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000
       nodePort: 30080
